# Generated by Django 5.2.6 on 2025-10-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='colour',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='colour',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='colour',
            field=models.CharField(default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('comp_off', 'Comp Off'), ('sick', 'Sick Leave'), ('annual', 'Annual Leave')], max_length=20, unique=True),
        ),
    ]
