# Generated by Django 5.2.6 on 2025-10-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_holiday_colour_holiday_holiday_type_leave_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
