# Generated by Django 5.2.6 on 2025-10-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavetype_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_leaves', models.IntegerField(default=0)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('leaves_remaining', models.IntegerField(default=0)),
                ('carry_forward', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2025)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leave_balances',
                'managed': False,
            },
        ),
    ]
