# Generated by Django 5.2.6 on 2025-10-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leavebalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'managed': True},
        ),
    ]
