# Generated by Django 5.2.6 on 2025-10-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_account_number_employee_bank_name_and_more'),
        ('leave', '0005_alter_leavebalance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='days_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
