# Generated by Django 5.2.6 on 2025-10-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_half_day_period_leave_is_half_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='accrual_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly accrual rate (e.g., 1.5 for annual leave)', max_digits=4),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='can_use_same_month',
            field=models.BooleanField(default=True, help_text="Whether leave can be used in the same month it's accrued"),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Whether this is an optional leave type'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward',
            field=models.IntegerField(default=0, help_text='Maximum days that can be carried forward to next year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('comp_off', 'Comp Off'), ('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('optional', 'Optional Leave')], max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='leavetype',
            table='leave_leavetype',
        ),
    ]
