# Generated by Django 5.2.6 on 2025-10-07 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('profile_picture', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin'), ('Super Admin', 'Super Admin')], max_length=20)),
                ('date_of_joining', models.DateField()),
                ('reporting_manager', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=8)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'hr_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeePassword',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hr.employee')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_employeepassword',
                'managed': True,
            },
        ),
    ]
