# Generated by Django 5.2.6 on 2025-10-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
