# Generated by Django 5.2.6 on 2025-10-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_probation_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('educational', 'Educational Certificate'), ('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('passbook', 'Bank Passbook'), ('offer_letter', 'Offer Letter'), ('salary_slip', 'Salary Slip'), ('bank_statement', 'Bank Statement'), ('experience_letter', 'Experience/Relieving Letter')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
            options={
                'db_table': 'employee_documents',
                'managed': True,
            },
        ),
    ]
