# Generated by Django 5.2.6 on 2025-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='employeedocument',
            table='hr_employee_documents',
        ),
    ]
